mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("site_app.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

site_app/urls.py
from django.urls import path
from site_app import views


urlpatterns=[
    path('', views.home_page, name="home")
]

site_app/models.py
from django.db import models
# Create your models here.

class MenuModel(models.Model):
    num = models.IntegerField(blank=True, null=True)
    name = models.CharField(max_length=20)
    url = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.name}"



class PortfolioModel(models.Model):
    caption = models.CharField(max_length=100, null=True, blank=True)
    images = models.ImageField(upload_to='media/')
    text = models.TextField(blank=True, null=True)


class AboutModel(models.Model):
    left_text = models.CharField(max_length=255,null=True, blank=True)
    right_text = models.CharField(max_length=255,null=True, blank=True)



class ContactFormModel(models.Model):
    name = models.CharField(max_length=20,blank=True, null=True)  # name
    phone = models.CharField(max_length=20,blank=True, null=True)  # phone
    email = models.EmailField(blank=True, null=True)
    message = models.TextField(blank=True, null=True)

    create_date = models.DateTimeField(auto_now_add=True, null=True, blank= True)

class InfoModel(models.Model):
    title = models.CharField(max_length=20)
    text = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.title}"

class IconModel(models.Model):
    icon = models.CharField(max_length=30)
    link = models.URLField()
    section = models.ForeignKey("InfoModel", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.icon}"


class UniqeModel(models.Model):
    pagename = models.CharField(max_length=50, blank=True, null=True)
    menu_bg = models.CharField(max_length=50, blank=True, null=True)
    header_bg = models.CharField(max_length=50, blank=True, null=True)
    header_avatar = models.ImageField(upload_to='media/')
    header_title = models.CharField(max_length=200)
    header_subtitle = models.CharField(max_length=200)
    portfolio_name = models.CharField(max_length=50)
    about_name = models.CharField(max_length=20, null=True, blank=True)
    about_btn_link = models.CharField(max_length=500, null=True, blank=True)    #https://startbootstrap.com/themes/freelancer/
    about_btn = models.CharField(max_length=20, null=True, blank=True)
    about_bg = models.CharField(max_length=50,null=True, blank=True)
    contact_name = models.CharField(max_length=20,blank=True, null=True)
    contact_btn = models.CharField(max_length=10, blank=True, null=True)
    contact_btn_color = models.CharField(max_length=50, null=True, blank=True)
    footer_bg = models.TextField(blank=True, null=True)
    copyright = models.CharField(max_length=50)

site_app/forms.py
from django import forms
from .models import ContactFormModel


class ContactForm(forms.ModelForm):

    class Meta:
        model = ContactFormModel
        fields = [
            "name", "email",
            "phone", "message"
        ]

        widgets = {
            "name": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Name"
            }),
            "email": forms.EmailInput(attrs={
                "class": "form-control",
                "placeholder": "Email Adress"
            }),
            "phone": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Phone Number"
            }),
            "message": forms.Textarea(attrs={
                "class": "form-control",
                "placeholder": "Message"
            })
        }

        labels = {
            "name": "Name",
            "email": "Email Adress",
            "phone": "Phone Number",
            "message": "Message"
        }

site_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, request
from site_app.models import *
from .forms import ContactForm
from django.contrib import messages
# Create your views here.


def home_page(request):
    context = {}
    context["form"] = ContactForm()
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(
                request,
                "Sizinle elaqe saxlanilacaq"
            )
            return redirect("/#contact")
        else:
            messages.error(
                request,
                "Form yanlishdir"
            )
            context["form"] = form

    context["menu_list"] = MenuModel.objects.filter().order_by('-num')
    context["portfolio_list"] = PortfolioModel.objects.all()
    context["about_list"] = AboutModel.objects.all()
    context["contact_list"] = ContactFormModel.objects.all()
    context["info_list"] = InfoModel.objects.all()
    context["icon_list"] = IconModel.objects.all()
    context["unique_list"] = UniqeModel.objects.first()

    return render(request, "index.html", context)

site_app/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Freelancer - Start Bootstrap Theme</title>
    {% load static %}
    <!-- Custom fonts for this theme -->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}  " rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet"
          type="text/css">

    <!-- Theme CSS -->
    <link href="{% static 'css/freelancer.min.css' %} " rel="stylesheet">
    <link href="{% static 'css/snackbar.css' %} " rel="stylesheet">
    <link href="{% static 'css/my_changes.css' %} " rel="stylesheet">


</head>

<body id="page-top">

<!-- Navigation -->
<nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">{{ unique_list.pagename }}</a>
        <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded"
                type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive"
                aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                {% for menu in menu_list %}
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger"
                           href="#{{ menu.url }}">{{ menu.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</nav>

<!-- Masthead -->

<header class="masthead bg-primary text-white text-center"
        style="background-color: {{ unique_list.header_bg }} !important;">
    <div class="container d-flex align-items-center flex-column">
        <!-- Masthead Avatar Image -->
        <img class="masthead-avatar mb-5 header_img" src="/media/{{ unique_list.header_avatar }}" alt="">

        <!-- Masthead Heading -->
        <h3 class="masthead-heading text-uppercase mb-0">{{ unique_list.header_title }}</h3>

        <!-- Icon Divider -->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon">
                <i class="fas fa-star"></i>
            </div>
            <div class="divider-custom-line"></div>
        </div>

        <!-- Masthead Subheading -->
        <p class="masthead-subheading font-weight-light mb-0">{{ unique_list.header_subtitle }}</p>
    </div>
</header>

<!-- Portfolio Section -->
<section class="page-section portfolio" id="portfolio">
    <div class="container">

        <!-- Portfolio Section Heading -->
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">{{ unique_list.portfolio_name }}</h2>

        <!-- Icon Divider -->
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon">
                <i class="fas fa-star"></i>
            </div>
            <div class="divider-custom-line"></div>
        </div>

        <!-- Portfolio Grid Items -->
        <div class="row">
            {% for portfolio in portfolio_list %}

                <!-- Portfolio Item 1 -->
                <div class="col-md-6 col-lg-4">
                    <div class="portfolio-item mx-auto" data-toggle="modal"
                         data-target="#portfolioModal{{ forloop.counter }}">
                        <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                            <div class="portfolio-item-caption-content text-center text-white">
                                <i class="fas fa-plus fa-3x"></i>
                            </div>
                        </div>
                        <img class="img-fluid portfolio_image" src="{{ portfolio.images.url }}" alt="">
                        <div class="container">
                            {#                            <div class="portfolio_caption">{{ portfolio.caption }}</div>#}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

    </div>
</section>

<!-- About Section -->
{% for about in about_list %}
    <section class="page-section bg-primary text-white mb-0" id="about"
             style="background-color: {{ unique_list.about_bg }}!important;">
        <div class="container">
            <!-- About Section Heading -->
            <h2 class="page-section-heading text-center text-uppercase text-white">{{ unique_list.about_name }}</h2>

            <!-- Icon Divider -->
            <div class="divider-custom divider-light">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon">
                    <i class="fas fa-star"></i>
                </div>
                <div class="divider-custom-line"></div>
            </div>

            <!-- About Section Content -->
            <div class="row">
                <div class="col-lg-4 ml-auto">
                    <p class="lead">{{ about.left_text }}</p>
                </div>
                <div class="col-lg-4 mr-auto">
                    <p class="lead">{{ about.right_text }}</p>
                </div>
            </div>

            <!-- About Section Button -->
            <div class="text-center mt-4">
                <a class="btn btn-xl btn-outline-light" href="{{ unique_list.about_btn_link }}">
                    <i class="fas fa-book mr-2"></i>
                    {{ unique_list.about_btn }}
                </a>
            </div>
        </div>
    </section>
{% endfor %}

<!-- Contact Section -->
<section class="page-section" id="contact">
    <div class="container">

        <!-- Contact Section Heading -->
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">{{ unique_list.contact_name }}</h2>

        <!-- Icon Divider -->
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon">
                <i class="fas fa-star"></i>
            </div>
            <div class="divider-custom-line"></div>
        </div>

        <!-- Contact Section Form -->
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19. -->
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="control-group">
                            <div class="form-group floating-label-form-group controls mb-0 pb-2">
                                <label>{{ field.label }}</label>
                                {{ field }}
                                {% if field.errors %}
                                    {% for err in field.errors %}
                                        <p class="help-block text-danger">{{ err }}</p>
                                    {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}
                    <br>
                    <div class="form-group">
                        <button type="submit" class="btn btn btn_css btn-xl"
                                id="sendMessageButton">{{ unique_list.contact_btn }}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

<!-- Footer -->
<footer class="footer text-center">
    <div class="container">
        <div class="row">

            {% for info in info_list %}
                {% if forloop.counter == 2 %}
                    <!-- Footer Social Icons -->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">{{ info.title }}</h4>
                        {% for icons in info.iconmodel_set.all %}
                            <a class="btn btn-outline-light btn-social mx-1" href="{{ icons.link }}">
                                <i class="fab fa-fw fa-{{ icons.icon }}"></i>
                            </a>
                        {% endfor %}
                    </div>
                {% else %}
                    <!-- Footer Location -->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">{{ info.title }}</h4>
                        <p class="lead mb-0">{{ info.text }}</p>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</footer>

<!-- Copyright Section -->
<section class="copyright py-4 text-center text-white">
    <div class="container">
        <small>{{ unique_list.copyright }}</small>
    </div>
</section>

<!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
<div class="scroll-to-top d-lg-none position-fixed ">
    <a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top">
        <i class="fa fa-chevron-up"></i>
    </a>
</div>
<div id="snackbar"></div>
<!-- Portfolio Modals -->
{% for portfolio in portfolio_list %}
    <!-- Portfolio Modal 1 -->
    <div class="portfolio-modal modal fade" id="portfolioModal{{ forloop.counter }}" tabindex="-1" role="dialog"
         aria-labelledby="portfolioModal1Label" aria-hidden="true">
        <div class="modal-dialog modal-xl" role="document">
            <div class="modal-content">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">
            <i class="fas fa-times"></i>
          </span>
                </button>
                <div class="modal-body text-center">
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-8">
                                <!-- Portfolio Modal - Title -->
                                <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">{{ portfolio.caption }}</h2>

                                <!-- Icon Divider -->
                                <div class="divider-custom">
                                    <div class="divider-custom-line"></div>
                                    <div class="divider-custom-icon">
                                        <i class="fas fa-star"></i>
                                    </div>
                                    <div class="divider-custom-line"></div>
                                </div>
                                <!-- Portfolio Modal - Image -->

                                <img class="img-fluid rounded mb-5" src="{{ portfolio.images.url }}" alt="">
                                <!-- Portfolio Modal - Text -->
                                <p class="mb-5">{{ portfolio.text }}</p>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endfor %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Plugin JavaScript -->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Contact Form JavaScript -->
<script src="{% static 'js/jqBootstrapValidation.js' %}"></script>
<script src="{% static 'js/contact_me.js' %}"></script>
<script>
    function snackbar(text) {
        var x = document.getElementById("snackbar");
        x.innerHTML = text;
        x.className = "show";
        setTimeout(function () {
            x.className = x.className.replace("show", "");
        }, 3000);
    }
    {% if messages %}
        {% for msg in messages %}
            snackbar("{{ msg }}");
        {% endfor %}
    {% endif %}
    {% if form.errors %}
        window.location.href = "#contact";
    {% endif %}
</script>


<!-- Custom scripts for this template -->
<script src="{% static 'js/freelancer.min.js' %}"></script>

</body>

</html>